import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const out='/Users/kevin/Documents/Codex/New project/outputs/01a0a636-1cf4-7961-ba49-c79cbb2a27ff';
const wb=Workbook.create();
const names=['Summary','Assumptions','Forecast','Valuation','Actuals','Checks'];
const sheets=Object.fromEntries(names.map(n=>[n,wb.worksheets.add(n)]));
const navy='#17324D',blue='#0000FF',green='#008000',gray='#E9EEF3';
const num='#,##0;(#,##0);"-"',pct='0.0%;(0.0%);"-"',price='$0.00;($0.00);"-"';
function v(s,a,x){sheets[s].getRange(a).values=[[x]];if(typeof x==='number')sheets[s].getRange(a).format.font.color=blue;}
function f(s,a,x){sheets[s].getRange(a).formulas=[[x]];sheets[s].getRange(a).format.font.color=s==='Summary'?navy:x.includes('!')?green:'#000000';}
function row(s,r,label){v(s,'C'+r,label);}
function band(s,r,label,end='L'){row(s,r,label);sheets[s].getRange(`C${r}:${end}${r}`).format.fill=gray;sheets[s].getRange(`C${r}:${end}${r}`).format.font.bold=true;}
function note(s,r,txt){row(s,r,txt);sheets[s].getRange(`C${r}`).format.font={name:'Arial',size:10,color:'#526171'};}
function total(s,r,end='L'){sheets[s].getRange(`C${r}:${end}${r}`).format.borders={top:{style:'thin',color:'#A6B3C0'}};sheets[s].getRange(`C${r}:${end}${r}`).format.font.bold=true;}
function per(s,r,start='E',end='L'){sheets[s].getRange(`${start}${r}:${end}${r}`).setNumberFormat(pct);sheets[s].getRange(`C${r}:${end}${r}`).format.font.italic=true;}
for(const n of names){const s=sheets[n];s.showGridLines=false;s.getRange('A1:N105').format.font={name:'Arial',size:10,color:'#000000'};s.getRange('A1:B105').format.columnWidth=2.5;s.getRange('C1:C105').format.columnWidth= forty();s.getRange('D1:D105').format.columnWidth=3;s.getRange('E1:L105').format.columnWidth=15;s.getRange('A1:N105').format.rowHeight=21;s.getRange('E1:L105').setNumberFormat(num);v(n,'C2',n==='Summary'?'Broadcom (AVGO) valuation':n);s.getRange('C2:L2').format.borders={bottom:{style:'thin',color:navy}};s.getRange('C2').format.font={name:'Arial',size:16,bold:true,color:navy};row(n,4,'Case selected');if(n!=='Assumptions')f(n,'E4',"='Assumptions'!G4");s.getRange('E4').format.font.color=green;s.getRange('E4').format.borders={preset:'outside',style:'dashed',color:'#9AA7B3'};s.getRange('E4').format.horizontalAlignment='center';if(!['Summary','Valuation'].includes(n))s.freezePanes.freezeRows(6);}
function forty(){return 43;}
sheets.Summary.tabColor=navy;sheets.Assumptions.tabColor='#50789D';sheets.Actuals.tabColor='#D8C8AD';
const urls={q3:'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial',q2:'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-second-quarter-fiscal-year-2026-financial',q1:'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-first-quarter-fiscal-year-2026-financial',sec:'https://www.sec.gov/Archives/edgar/data/1730168/000173016826000080/avgo-20260802.htm',market:'https://www.historicalstockprice.com/avgo-historical-stock-prices/'};
// Raw disclosures; all financial amounts and shares in millions.
note('Actuals',5,'USD millions, except per-share data. Financial disclosures are unaudited.');
sheets.Actuals.getRange('E6:F6').values=[['9M:26 actual','Q3:26 actual']];
const actual=[['Revenue',71089,29591],['Semiconductor revenue',48363,20839],['Infrastructure software revenue',22726,8752],['Non-GAAP operating income',47849,20095],['GAAP operating income',35306,15955],['Stock-based compensation',6287,2019],['Acquisition amortization',5942,2006],['Restructuring and other charges',312,115],['Acquisition costs',2,0],['Cash from operations',32950,14197],['Capital expenditures (positive)',1013,532],['Reported free cash flow',31937,13665],['Depreciation',484,null],['Non-GAAP net income',38631,16372],['Non-GAAP diluted shares',4945,4937],['Non-GAAP interest expense (positive)',2194,703]];
actual.forEach((a,i)=>{row('Actuals',i+7,a[0]);v('Actuals','E'+(i+7),a[1]);if(a[2]!==null)v('Actuals','F'+(i+7),a[2]);});
band('Actuals',24,'Balance sheet / market inputs','F');
const raw=[['Cash at August 2, 2026',23975],['Short-term debt at August 2',2252],['Long-term debt at August 2',57167],['Basic shares at August 28',4773.629865],['Closing price, September 14, 2026',344.72],['Valuation / price date',new Date('2026-09-14T00:00:00Z')],['Last reported balance sheet date',new Date('2026-08-02T00:00:00Z')],['Q4:26 fiscal end',new Date('2026-11-01T00:00:00Z')],['Q4:26 revenue guidance',34800],['Q4:26 AI revenue guidance (rounded)',21700],['Q4:26 non-GAAP operating margin',.66],['Q1:26 AI revenue (rounded)',8400],['Q2:26 AI revenue (rounded)',10800],['Q3:26 AI revenue (rounded)',16700],['Maximum AI lease backstop exposure',29000]];
raw.forEach((a,i)=>{row('Actuals',i+25,a[0]);v('Actuals','E'+(i+25),a[1]);});sheets.Actuals.getRange('E29').setNumberFormat(price);sheets.Actuals.getRange('E30:E32').setNumberFormat('mmm d, yyyy');sheets.Actuals.getRange('E35').setNumberFormat(pct);
// Sources are consolidated beside raw data, with short locators and full URLs.
v('Actuals','H6','Source / locator');const sourceNotes=[[7,'Q3 release: financial highlights / reconciliations',urls.q3],[10,'Q3 10-Q: pages 2–5 and Note 9 (segment data)',urls.sec],[25,'Q3 10-Q: balance sheet and cover share count',urls.sec],[29,'September 14, 2026 close; retrieved September 15',urls.market],[33,'Q3 release: Q4 outlook and AI revenue guidance',urls.q3],[36,'Q1 release: AI revenue in CEO commentary',urls.q1],[37,'Q2 release: AI revenue in CEO commentary',urls.q2],[39,'Q3 10-Q: Note 10, contingent maximum, not debt',urls.sec]];
for(const [i,[originalRow,t,u]] of sourceNotes.entries()){const r=7+i*4;v('Actuals','H'+r,`Rows ${originalRow}: ${t}`);v('Actuals','H'+(r+1),u);sheets.Actuals.getRange('H'+(r+1)).format.wrapText=true;sheets.Actuals.getRange(`H${r+1}:H${r+2}`).format.rowHeight=34;}
sheets.Actuals.getRange('H1:H105').format.columnWidth=65;
note('Actuals',42,'AI disclosures are rounded; derived non-AI revenue is therefore approximate.');
note('Actuals',43,'Backstop: no payments made; fair value immaterial at reporting date.');
// One active scenario feeds all forecast periods.
v('Assumptions','E4',1);f('Assumptions','G4','=CHOOSE(E4,"Base","Bear","Bull")');v('Assumptions','H4','1 Base / 2 Bear / 3 Bull');sheets.Assumptions.getRange('E4').dataValidation={rule:{type:'list',values:['1','2','3']}};
note('Assumptions',5,'Blue numbers are editable. Forecast drivers are analyst assumptions unless linked to guidance.');
const scalars=[[7,'Market price',"='Actuals'!E29"],[8,'Valuation date',"='Actuals'!E30"],[9,'Diluted shares held constant',"='Actuals'!F21"],[10,'Q4 software growth vs Q3',.03],[11,'Q4 revenue vs guidance',1],[12,'Q4 AI revenue vs guidance',1]];
for(const [r,l,x] of scalars){row('Assumptions',r,l);typeof x==='string'?f('Assumptions','E'+r,x):v('Assumptions','E'+r,x);}
sheets.Assumptions.getRange('E7').setNumberFormat(price);sheets.Assumptions.getRange('E8').setNumberFormat('mmm d, yyyy');sheets.Assumptions.getRange('E10:E12').setNumberFormat(pct);
sheets.Assumptions.getRange('E14:J14').values=[['Q4:26 E','FY:27 E','FY:28 E','FY:29 E','FY:30 E','FY:31 E']];
const drivers=[
 [16,'AI revenue growth',[0,1,.55,.30,.20,.12],[0,.60,.30,.20,.12,.08],[0,1.25,.70,.40,.25,.15]],
 [21,'Non-AI semiconductor growth',[0,.08,.06,.05,.04,.03],[0,0,.02,.03,.03,.02],[0,.12,.10,.08,.06,.04]],
 [26,'Software revenue growth',[0,.20,.15,.12,.10,.08],[0,.10,.08,.06,.05,.04],[0,.28,.22,.16,.12,.10]],
 [31,'Non-GAAP operating margin',[.66,.65,.64,.63,.62,.61],[.66,.61,.60,.59,.58,.57],[.66,.68,.68,.67,.66,.65]],
 [36,'SBC / revenue',[.07,.06,.055,.05,.05,.05],[.07,.08,.075,.07,.07,.07],[.07,.05,.045,.04,.04,.04]],
 [41,'Normalized tax rate',[.17,.17,.17,.17,.17,.17],[.19,.19,.19,.19,.19,.19],[.16,.16,.16,.16,.16,.16]],
 [46,'Depreciation / revenue',[.007,.007,.007,.007,.007,.007],[.008,.008,.008,.008,.008,.008],[.006,.006,.006,.006,.006,.006]],
 [51,'Capex / revenue',[.02,.02,.02,.02,.02,.02],[.025,.025,.025,.025,.025,.025],[.018,.018,.018,.018,.018,.018]],
 [56,'Operating NWC / annual revenue',[.15,.15,.15,.15,.15,.15],[.20,.20,.20,.20,.20,.20],[.12,.12,.12,.12,.12,.12]]];
for(const [r,label,...cases] of drivers){band('Assumptions',r,label+' — active','J');for(let k=0;k<3;k++){row('Assumptions',r+1+k,['Base','Bear','Bull'][k]);sheets.Assumptions.getRange(`E${r+1+k}:J${r+1+k}`).values=[cases[k]];sheets.Assumptions.getRange(`E${r+1+k}:J${r+1+k}`).format.font.color=blue;}for(let k=0;k<6;k++){let c=String.fromCharCode(69+k);f('Assumptions',c+r,`=IF(ISNUMBER(CHOOSE($E$4,${c}${r+1},${c}${r+2},${c}${r+3})),CHOOSE($E$4,${c}${r+1},${c}${r+2},${c}${r+3}),NA())`);}sheets.Assumptions.getRange(`E${r}:J${r+3}`).setNumberFormat(pct);sheets.Assumptions.getRange(`C${r}:J${r+3}`).format.font.italic=true;}
band('Assumptions',62,'Valuation assumptions','H');sheets.Assumptions.getRange('E63:H63').values=[['Active','Base','Bear','Bull']];
const vals=[[64,'WACC',.11,.125,.10],[65,'Terminal growth',.03,.025,.035],[66,'Forward non-GAAP P/E',28,22,34],[67,'Annual non-GAAP interest expense',2812,2812,2812],[68,'Backstop loss reserve',0,2900,0]];
for(const [r,l,...x] of vals){row('Assumptions',r,l);sheets.Assumptions.getRange(`F${r}:H${r}`).values=[x];sheets.Assumptions.getRange(`F${r}:H${r}`).format.font.color=blue;f('Assumptions','E'+r,`=IF(ISNUMBER(CHOOSE($E$4,F${r},G${r},H${r})),CHOOSE($E$4,F${r},G${r},H${r}),NA())`);}sheets.Assumptions.getRange('E64:H65').setNumberFormat(pct);sheets.Assumptions.getRange('E66:H66').setNumberFormat('0.0"x"');
for(const r of [32,33,34])f('Assumptions','E'+r,"='Actuals'!E35");
for(const c of ['F','G','H'])f('Assumptions',c+'67',"='Actuals'!F22*4");
f('Assumptions','G68',"='Actuals'!E39*10%");
note('Assumptions',71,'Cases are illustrative forecasts, not consensus estimates or company guidance.');
note('Assumptions',72,'AI growth fades after FY:27; software and non-AI growth use separate drivers.');
note('Assumptions',73,'Margins allow for AI product mix. Rates and P/E multiples are judgmental inputs.');
note('Assumptions',74,'Interest assumes Q3 non-GAAP expense × 4; debt and shares remain constant.');
note('Assumptions',75,'Bear reserve is 10% of the disclosed backstop maximum; no default is assumed in Base.');
note('Assumptions',76,'Q4 growth rows are unused; Q4 revenue uses guidance and the software growth input.');
// Forecast: 9 months + Q4 = fiscal year estimate, followed by five annual forecasts.
note('Forecast',5,'USD millions, except EPS. E = estimate. NWC = net working capital.');
sheets.Forecast.getRange('E6:L6').values=[['9M:26 A','Q4:26 E','FY:26 E','FY:27 E','FY:28 E','FY:29 E','FY:30 E','FY:31 E']];
const labels={8:'AI semiconductor revenue',9:'Other semiconductor revenue',10:'Infrastructure software revenue',11:'Total revenue',12:'Revenue growth vs prior fiscal year',14:'Non-GAAP operating margin',15:'Non-GAAP operating income',16:'SBC / revenue',17:'Stock-based compensation',18:'Operating profit after SBC',20:'Normalized tax rate',21:'Tax on operating profit after SBC',22:'NOPAT after SBC',24:'Depreciation',25:'Capital expenditures',27:'Operating NWC / annual revenue',28:'Closing operating NWC (modeled)',29:'Opening operating NWC (modeled)',30:'Increase in operating NWC',32:'Unlevered cash flow after SBC',34:'Non-GAAP interest expense',35:'Non-GAAP pretax income (modeled)',36:'Normalized income tax',37:'Non-GAAP net income',38:'Diluted shares',39:'Non-GAAP EPS',41:'Reported operating cash flow',42:'Reported free cash flow'};
Object.entries(labels).forEach(([r,l])=>row('Forecast',r,l));
f('Forecast','E8',"=SUM('Actuals'!E36:E38)");f('Forecast','E9',"='Actuals'!E8-E8");f('Forecast','E10',"='Actuals'!E9");f('Forecast','E11','=SUM(E8:E10)');
for(const [r,sr] of [[15,10],[17,12],[24,19],[25,17],[34,22],[37,20],[38,21],[41,16],[42,18]])f('Forecast','E'+r,`='Actuals'!E${sr}`);
f('Forecast','E14','=E15/E11');f('Forecast','E16','=E17/E11');f('Forecast','E18','=E15-E17');f('Forecast','E39','=E37/E38');
f('Forecast','F8',"='Actuals'!E34*'Assumptions'!E12");f('Forecast','F10',"='Actuals'!F9*(1+'Assumptions'!E10)");f('Forecast','F11',"='Actuals'!E33*'Assumptions'!E11");f('Forecast','F9','=F11-F8-F10');
for(let j=7;j<=12;j++){const c=String.fromCharCode(64+j),p=String.fromCharCode(63+j);if(j===7){for(const r of [8,9,10,11,15,17,18,24,25,34,37])f('Forecast',c+r,`=E${r}+F${r}`);f('Forecast','G14','=G15/G11');f('Forecast','G16','=G17/G11');f('Forecast','G38','=(E38*3+F38)/4');f('Forecast','G39','=G37/G38');continue;}const ac=String.fromCharCode(62+j);for(const [r,ar] of [[8,16],[9,21],[10,26]])f('Forecast',c+r,`=${p}${r}*(1+'Assumptions'!${ac}${ar})`);f('Forecast',c+'11',`=SUM(${c}8:${c}10)`);f('Forecast',c+'12',`=${c}11/${p}11-1`);}
for(const [c,ac] of [['F','E'],['H','F'],['I','G'],['J','H'],['K','I'],['L','J']]){for(const [r,ar] of [[14,31],[16,36],[20,41],[27,56]])f('Forecast',c+r,`='Assumptions'!${ac}${ar}`);f('Forecast',c+'15',`=${c}11*${c}14`);f('Forecast',c+'17',`=${c}11*${c}16`);f('Forecast',c+'18',`=${c}15-${c}17`);f('Forecast',c+'21',`=${c}18*${c}20`);f('Forecast',c+'22',`=${c}18-${c}21`);f('Forecast',c+'24',`=${c}11*'Assumptions'!${ac}46`);f('Forecast',c+'25',`=${c}11*'Assumptions'!${ac}51`);f('Forecast',c+'28',`=${c==='F'?'G':c}11*${c}27`);f('Forecast',c+'29',c==='F'?"=E11*4/3*'Assumptions'!E56":`=${c==='H'?'F':String.fromCharCode(c.charCodeAt(0)-1)}28`);f('Forecast',c+'30',`=${c}28-${c}29`);f('Forecast',c+'32',`=${c}22+${c}24-${c}25-${c}30`);f('Forecast',c+'34',`='Assumptions'!E67${c==='F'?'/4':''}`);f('Forecast',c+'35',`=${c}15-${c}34`);f('Forecast',c+'36',`=${c}35*${c}20`);f('Forecast',c+'37',`=${c}35-${c}36`);f('Forecast',c+'38',"='Assumptions'!E9");f('Forecast',c+'39',`=${c}37/${c}38`);}
for(const r of [12,14,16,20,27])per('Forecast',r);sheets.Forecast.getRange('E39:L39').setNumberFormat(price);for(const r of [11,15,18,22,32,37,39,42])total('Forecast',r);
note('Forecast',45,'DCF deducts SBC and holds diluted shares flat; no extra future dilution or buybacks modeled.');
note('Forecast',46,'Non-GAAP profit already excludes acquisition amortization; only depreciation is added back.');
note('Forecast',47,'NWC is modeled as a share of annual sales. Q4 opens from annualized 9M sales × Q4 NWC rate.');
note('Forecast',48,'9M cash flow is reported levered FCF. Forecast DCF cash flow is unlevered and after SBC.');
note('Forecast',49,'Historical normalized taxes / modeled UFCF are left blank; no invented actual cash-flow bridge.');
note('Forecast',50,'P/E earnings exclude SBC and acquisition amortization; other income is assumed zero.');
// Valuation date and stub discounting. All values are current, not one-year targets.
note('Valuation',5,'USD millions, except per share. Current fair value as of September 14, 2026.');
sheets.Valuation.getRange('E7:J7').values=[['Q4 remainder','FY:27 E','FY:28 E','FY:29 E','FY:30 E','FY:31 E']];
row('Valuation',8,'Years from valuation date');row('Valuation',9,'Full-period unlevered cash flow');row('Valuation',10,'Share of period remaining');row('Valuation',11,'Cash flow to discount');row('Valuation',12,'Discount factor (end period)');row('Valuation',13,'Present value of cash flow');
f('Valuation','E8',"=('Actuals'!E32-'Assumptions'!E8)/365");f('Valuation','E10',"=('Actuals'!E32-'Assumptions'!E8)/('Actuals'!E32-'Actuals'!E31)");
for(let i=0;i<6;i++){const c=String.fromCharCode(69+i),fc=i===0?'F':String.fromCharCode(71+i);if(i>0){f('Valuation',c+'8',`=E8+${i}`);v('Valuation',c+'10',1);}f('Valuation',c+'9',`='Forecast'!${fc}32`);f('Valuation',c+'11',`=${c}9*${c}10`);f('Valuation',c+'12',`=1/(1+'Assumptions'!$E$64)^${c}8`);f('Valuation',c+'13',`=${c}11*${c}12`);}
sheets.Valuation.getRange('E8:J8').setNumberFormat('0.00');sheets.Valuation.getRange('E10:J10').setNumberFormat(pct);sheets.Valuation.getRange('E12:J12').setNumberFormat('0.000x');
const vr={16:'PV of explicit cash flows',17:'Terminal cash flow',18:'Terminal value at FY:31 end',19:'Present value of terminal value',20:'Enterprise value',21:'Latest reported debt',22:'Latest reported cash',23:'Backstop loss reserve',24:'Equity value',25:'Diluted shares',26:'DCF fair value / share',27:'Upside / (downside) vs price',28:'Terminal value / enterprise value',31:'FY:27 non-GAAP EPS',32:'Assumed forward P/E',33:'P/E indicated current value / share',34:'P/E upside / (downside)',35:'Market forward P/E'};Object.entries(vr).forEach(([r,l])=>row('Valuation',r,l));
const vf={16:'=SUM(E13:J13)',17:"=J9*(1+'Assumptions'!E65)",18:"=IF('Assumptions'!E64>'Assumptions'!E65,E17/('Assumptions'!E64-'Assumptions'!E65),NA())",19:'=E18*J12',20:'=SUM(E16,E19)',21:"=SUM('Actuals'!E26:E27)",22:"='Actuals'!E25",23:"='Assumptions'!E68",24:'=E20-E21+E22-E23',25:"='Assumptions'!E9",26:'=E24/E25',27:"=E26/'Assumptions'!E7-1",28:'=E19/E20',31:"='Forecast'!H39",32:"='Assumptions'!E66",33:'=E31*E32',34:"=E33/'Assumptions'!E7-1",35:"='Assumptions'!E7/E31"};for(const [r,x] of Object.entries(vf))f('Valuation','E'+r,x);for(const r of [26,31,33])sheets.Valuation.getRange('E'+r).setNumberFormat(price);for(const r of [27,28,34])per('Valuation',r,'E','E');for(const r of [32,35])sheets.Valuation.getRange('E'+r).setNumberFormat('0.0"x"');for(const r of [20,24,26,33])total('Valuation',r,'E');
v('Valuation','G16','DCF sensitivity ($/share)');v('Valuation','G17','WACC / growth');
for(let k=0;k<5;k++){const c=String.fromCharCode(72+k);f('Valuation',c+'18',`='Assumptions'!$E$65+${(k-2)*.005}`);}
for(let i=0;i<5;i++){const r=19+i;f('Valuation','G'+r,`='Assumptions'!$E$64+${(i-2)*.01}`);for(let k=0;k<5;k++){const c=String.fromCharCode(72+k),pvs=['E','F','G','H','I','J'].map(x=>`$${x}$11/(1+$G${r})^$${x}$8`).join('+');f('Valuation',c+r,`=IF($G${r}>${c}$18,(${pvs}+(('Forecast'!$L$22+'Forecast'!$L$24-'Forecast'!$L$25)*(1+${c}$18)-'Forecast'!$L$28*${c}$18)/($G${r}-${c}$18)/(1+$G${r})^$J$8-$E$21+$E$22-$E$23)/$E$25,NA())`);}}
v('Valuation','G26','Terminal-year cash flow (FY:32)');
for(const [r,l,x] of [[27,'Revenue',"='Forecast'!L11*(1+'Assumptions'!E65)"],[28,'NOPAT after SBC',"=J27*('Forecast'!L14-'Forecast'!L16)*(1-'Forecast'!L20)"],[29,'Depreciation',"=J27*'Assumptions'!J46"],[30,'Capex',"=J27*'Assumptions'!J51"],[31,'Increase in NWC',"='Forecast'!L28*'Assumptions'!E65"],[32,'Terminal cash flow','=J28+J29-J30-J31']]){v('Valuation','G'+r,l);f('Valuation','J'+r,x);}
f('Valuation','E17','=J32');
sheets.Valuation.getRange('H18:L18').setNumberFormat(pct);sheets.Valuation.getRange('G19:G23').setNumberFormat(pct);sheets.Valuation.getRange('H19:L23').setNumberFormat(price);sheets.Valuation.getRange('H19:L23').conditionalFormats.add('colorScale',{colors:['#FBE9E7','#FFFFFF','#DCE9F5']});sheets.Valuation.getRange('J21').format.borders={preset:'outside',style:'medium',color:navy};
note('Valuation',38,'DCF uses a prorated Q4 remainder and five full years; annual end dates use one-year spacing.');
note('Valuation',39,'Latest reported cash/debt are held at August 2 balances; interim cash generation is not rolled forward.');
note('Valuation',40,'Terminal revenue grows at g; margins / capex ratios stay flat and incremental NWC resets to g.');
note('Valuation',41,'P/E is a current forward multiple on FY:27 EPS, not an exit price or discounted future target.');
note('Valuation',42,'No blended target: DCF is the primary method; non-GAAP P/E is a separate cross-check.');
// Output summary.
note('Summary',5,'USD millions, except prices and EPS. Current fair value; prepared September 15, 2026.');
const sr={7:['Reference price',"='Assumptions'!E7"],8:['Price date',"='Assumptions'!E8"],10:['DCF fair value / share',"='Valuation'!E26"],11:['Upside / (downside)',"='Valuation'!E27"],13:['P/E indicated value / share',"='Valuation'!E33"],14:['Assumed forward P/E',"='Valuation'!E32"],16:['WACC',"='Assumptions'!E64"],17:['Terminal growth',"='Assumptions'!E65"],18:['PV terminal / enterprise value',"='Valuation'!E28"]};for(const [r,[l,x]] of Object.entries(sr)){row('Summary',r,l);f('Summary','E'+r,x);}for(const r of [7,10,13])sheets.Summary.getRange('E'+r).setNumberFormat(price);sheets.Summary.getRange('E8').setNumberFormat('mmm d, yyyy');sheets.Summary.getRange('E14').setNumberFormat('0.0"x"');for(const r of [11,16,17,18])per('Summary',r,'E','E');total('Summary',10,'E');total('Summary',13,'E');
sheets.Summary.getRange('C22:G22').values=[['Fiscal year','Revenue','AI revenue','UFCF after SBC','Non-GAAP EPS']];for(let i=0;i<5;i++){const r=23+i,fc=String.fromCharCode(72+i);v('Summary','C'+r,'FY:'+String(27+i)+' E');f('Summary','D'+r,`='Forecast'!${fc}11`);f('Summary','E'+r,`='Forecast'!${fc}8`);f('Summary','F'+r,`='Forecast'!${fc}32`);f('Summary','G'+r,`='Forecast'!${fc}39`);}sheets.Summary.getRange('D22:G27').format.columnWidth=19;sheets.Summary.getRange('D23:F27').setNumberFormat(num);sheets.Summary.getRange('G23:G27').setNumberFormat(price);
const chart=sheets.Summary.charts.add('line',sheets.Summary.getRange('C22:E27'));chart.title='Revenue forecast ($M)';chart.titleTextStyle.typeface='Arial';chart.titleTextStyle.fontSize=12;chart.setPosition('G7','M20');chart.legend={position:'bottom',textStyle:{typeface:'Arial',fontSize:10}};chart.xAxis={axisType:'textAxis',textStyle:{typeface:'Arial',fontSize:10}};chart.yAxis={numberFormatCode:'#,##0',numberFormatSourceLinked:false,textStyle:{typeface:'Arial',fontSize:10}};chart.series.items.forEach((x,i)=>{x.line={fill:i?'#C64747':navy,style:'solid',width:2};});
band('Summary',30,'Key model choices','L');note('Summary',32,'Change the case selector and blue inputs on Assumptions to test your own investment view.');note('Summary',33,'Q4 starts from company guidance. FY:27–31 growth, margins, WACC and multiples are analyst assumptions.');note('Summary',34,'DCF includes the economic cost of SBC; the non-GAAP earnings multiple excludes SBC.');note('Summary',35,'Valuation is sensitive to AI demand, customer concentration, margins and terminal growth.');note('Summary',36,'Net debt uses the latest reported balance sheet. No intervening cash, buybacks or debt changes are estimated.');
// Terminal checks do not drive any business output.
sheets.Checks.getRange('E6:F6').values=[['Difference / test','Status']];const checks=[['9M segment revenue reconciliation',"=SUM('Actuals'!E8:E9)-'Actuals'!E7"],['Q3 segment revenue reconciliation',"=SUM('Actuals'!F8:F9)-'Actuals'!F7"],['9M GAAP to non-GAAP EBIT',"=SUM('Actuals'!E11:E15)-'Actuals'!E10"],['9M reported FCF reconciliation',"='Actuals'!E16-'Actuals'!E17-'Actuals'!E18"],['Q3 reported FCF reconciliation',"='Actuals'!F16-'Actuals'!F17-'Actuals'!F18"],['FY:26 revenue bridge',"='Forecast'!G11-'Actuals'!E7-'Forecast'!F11"],['Q4 segment revenue reconciliation',"=SUM('Forecast'!F8:F10)-'Forecast'!F11"],['DCF sensitivity at active inputs',"='Valuation'!J21-'Valuation'!E26"],['Enterprise to equity bridge',"='Valuation'!E24-('Valuation'!E20-'Valuation'!E21+'Valuation'!E22-'Valuation'!E23)"],['WACC exceeds terminal growth',"=IF('Assumptions'!E64>'Assumptions'!E65,0,1)"],['Q4 non-AI revenue nonnegative',"=IF('Forecast'!F9>=0,0,1)"],['Valuation date inside Q4',"=IF(AND('Assumptions'!E8>='Actuals'!E31,'Assumptions'!E8<'Actuals'!E32),0,1)"],['Share count positive',"=IF('Assumptions'!E9>0,0,1)"],['FY:28 opening NWC roll-forward',"='Forecast'!I29-'Forecast'!H28"]];checks.forEach(([l,x],i)=>{const r=i+7;row('Checks',r,l);f('Checks','E'+r,x);f('Checks','F'+r,`=IF(ABS(E${r})<0.01,"OK","REVIEW")`);});sheets.Checks.getRange('E7:E20').setNumberFormat('0.00;(0.00);0.00');sheets.Checks.getRange('E7:F20').format.font.color='#000000';sheets.Checks.getRange('F7:F20').format.horizontalAlignment='center';sheets.Checks.getRange('E7:F20').conditionalFormats.addCustom('ABS($E7)>=0.01',{fill:'#FCE4D6',font:{color:'#9C0006',bold:true}});note('Checks',23,'Differences use a $0.01 million / $0.01 per-share tolerance, as appropriate.');
for(const [s,rng] of [['Actuals','E6:F6'],['Assumptions','E14:J14'],['Assumptions','E63:H63'],['Forecast','E6:L6'],['Valuation','E7:J7'],['Summary','C22:G22'],['Checks','E6:F6']]){sheets[s].getRange(rng).format.fill=navy;sheets[s].getRange(rng).format.font.color='#FFFFFF';sheets[s].getRange(rng).format.font.bold=true;sheets[s].getRange(rng).format.horizontalAlignment='center';}
// Verify cases and a later-year driver through the same live build, then restore.
const snapshots=[];for(const c of [1,2,3]){v('Assumptions','E4',c);wb.recalculate();snapshots.push({case:c,dcf:sheets.Valuation.getRange('E26').values,pe:sheets.Valuation.getRange('E33').values});}v('Assumptions','E4',1);
const before=sheets.Valuation.getRange('E26').values[0][0];v('Assumptions','J17',.20);wb.recalculate();const changed=sheets.Valuation.getRange('E26').values[0][0];if(changed===before)throw new Error('Later-period driver did not update valuation');v('Assumptions','J17',.12);
// Blank unselected case leaves Base intact; selected missing input remains visible.
v('Assumptions','J18',null);wb.recalculate();const blankInactive=sheets.Valuation.getRange('E26').values[0][0];if(typeof blankInactive!=='number')throw new Error('Inactive blank blocked Base');v('Assumptions','E4',2);wb.recalculate();const blankSelected=sheets.Valuation.getRange('E26').values[0][0];if(typeof blankSelected==='number')throw new Error('Selected blank did not surface');v('Assumptions','J18',.08);v('Assumptions','E4',1);
wb.recalculate();
await fs.mkdir(out,{recursive:true});
console.log(JSON.stringify({snapshots,driverChange:{before,changed},blankSelected}));
console.log((await wb.inspect({kind:'table',range:'Summary!C7:E18',include:'values,formulas',tableMaxRows:12,tableMaxCols:3,maxChars:3000})).ndjson);
console.log((await wb.inspect({kind:'table',range:'Checks!C7:F20',include:'values',tableMaxRows:14,tableMaxCols:4,maxChars:3000})).ndjson);
console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:30},summary:'Final formula error scan'})).ndjson);
await (await SpreadsheetFile.exportXlsx(wb)).save(out+'/AVGO_Valuation_Model.xlsx');
for(const [n,rng] of [['Summary','C2:M36'],['Assumptions','C2:J39'],['Assumptions','C41:J76'],['Forecast','C2:L42'],['Valuation','C2:L35'],['Actuals','C2:F39'],['Checks','C2:F23']]){const blob=await wb.render({sheetName:n,range:rng,scale:1.5,format:'png'});await fs.writeFile(out+'/'+n+'_'+rng.replace(':','-')+'.png',new Uint8Array(await blob.arrayBuffer()));}
await fs.writeFile(out+'/validation.json',JSON.stringify({snapshots,driverChange:{before,changed},blankSelected},null,2));
